[toolchain]
anchor_version = "0.32.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
exodus_core = "A59QJtaFuap54ZBq8GfMDAAW7tWCJ4hHAGrbL8v22ZRU"
exodus_tbill_vault = "2zwyHvFnB7TacEbTWwyceX2JkAm8hDFLdK1pxew33Wgz"

[programs.localnet]
exodus_core = "A59QJtaFuap54ZBq8GfMDAAW7tWCJ4hHAGrbL8v22ZRU"
exodus_tbill_vault = "2zwyHvFnB7TacEbTWwyceX2JkAm8hDFLdK1pxew33Wgz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"
